### ISSUE TITLE
Missing back slash in PATH

### ISSUE THREAD

**Issue by ghost** [midnight-coding/WampServer-PHP-CLI-Version-Changer#1]
Hi there, when using your script on my Windows 10 machine it adds this line in my PATH: `C:\wamp64\bin\phpphp7.2.4`. With the last backslash missing.

I've fixed it by adding back the slash at the end of line 28: `set $pathToPhpFolders=bin\php\`. And also deleting php from the PATH system vars, which was overwriting the targeted one located in the user vars. 

Not sure if I'm the only one facing this or not, anyway thx for this great script 👍

**Comment by midnight-coding** [comment]
Hi There

Thank you for your feedback.

This has now been fixed in v1.1.1 by adding qty 2 backslashes.
- One in line 141.
- One in line 241.

This allows for an unpolluted (non-backslashed) default variable on line 28. I prefer not to have trailing backslashes on paths where possible as I believe an 'intelligent' script should take care of it.

PS: Currently, this script has been intentionally programmed to only update the users environmental variable path and not the systems environmentals path as the use of this script is more user based than system (all users) based.

Regarding the php entry in your system environmental path, another program would have added this at some time, perhaps another WAMP / LAMP server you may have installed previously. Depending on the specificity of the php path, it may have very well overridden the users environmental path setting rendering this script ineffective. Currently WampServer does not add any entries to the user or system environmental paths, though should this change then this script will need to take another approach (if the developers of WampServer do not allow separate adjustment of the php cli version).

Thank you for appreciating this script. It is greatly appreciated.
