### ISSUE TITLE
after finish all the steps still php -v says PHP 5.6.31 (cli)

### ISSUE THREAD

**Issue by johnef** [midnight-coding/WampServer-PHP-CLI-Version-Changer#2]
I see that my current version is `7.1.9` but when I run `CMD` and try `php -v` it gives `PHP 5.6.31 (cli)`

**Comment by midnight-coding** [comment]
@johnef 

It appears that your environment 'path' variable is referencing PHP version 5.6.31 prior to your selected PHP version 7.1.9

Windows constructs the environment 'path' variable by appending the user path to the system path. IE: 'path' = system path; user path;

When using this script, the list of available PHP versions is built from the “bin\php” folder, typically located at “C:\wamp\bin\php\”. Upon selecting an available version, its path is appended to the environment user path.

There are occasions when a PHP path within the environment user path is not at the very end. This is often caused by a newly installed program adding its own path to the end of the environment user path. This script is smart enough to detect this and still remove the old version if the selection changes.

What this script cannot do (at the moment) is:

1.	Remove from the environment user path multiple PHP version paths.
2.	Remove from the environment user path any PHP version path(s) that are not in the list of available PHP versions.

These two issues have been flagged as top priority for the next update.

To resolve your current issue, you should:

1.	Manually remove all references to any PHP version path(s) in your environment user path.
2.	Manually remove all references to any PHP version path(s) in your environment system path.
3.	Run the WampServer PHP CLI Version Changer script again.

If this fails to resolve your issue then please respond with a snapshot of your environment user and system path variables along with the list of your installed PHP version addons. IE: List of folders in “C:\wamp\bin\php\”.

Thank you.
